### PR TITLE
Add Amiga 1000 CPLD design

### PR DESCRIPTION
**Pull request by LinuxJedi**
Needs to be a different orientation to the Amiga 500 design. Currently
untested.

### CODE REVIEW

**Comment by SirCathal** [comment]
Thank you very much!, we ordered some of them. I think it will take one ore two weeks to get the PCBs.
I will report as soon as I have one in my A1000.

**Comment by SirCathal** [comment]
The Chips are delivered, but the PCBs are still on the way... Have to wait some more days to test.

**Comment by LinuxJedi** [comment]
> The Chips are delivered, but the PCBs are still on the way... Have to wait some more days to test.

Cool. If it helps, IanSB has dropped a beta which allows single-button-mode on the recovery menu:

https://github.com/IanSB/RGBtoHDMI/releases/tag/fddfad7

Just need to set single_button_mode=1 in Profiles/Default.txt. You can select either the 6-12bit RGB or BBC firmware. The only real difference is which profile it defaults to, you can then change the profile to Amiga with the button.

**Comment by SirCathal** [comment]
@LinuxJedi Thanx, I used Ian's Beta Versions for a long time and did some testing for him to get the variable scanline mode working. So I will continue this and check that option.  I'm really excited to test your Adapter in my A1000. If the sparkles are gone, the PiStorm Project will be the next thing to test with the A1000 ;-) 

But there is one question I have.
The A1000 is normally missing 2 signals at the Denise socket, that newer Amigas have. 
To get more than a black screen with the old Adapter, I hat to get those signals to the socket.

The first one is CSync. That was easy, I soldered a cable from pin 8 on UA6 to pin 32 of the Denise socket under the motherboard.
The second one was more tricky, because it's _CDAC which is not available in the A1000. only the non inverted CDAC is there.
But C0pperdragon and Ian taught that it should work with that. So I did this Change:
https://github.com/c0pperdragon/Amiga-Digital-Video/issues/28#issuecomment-798964142 
To get CDAC to the Denese socket as well. 
With those Changes I got rid of the black screen and with the second I removed the purple shadows I had before
But everything with strong sparkles because of the old Adapter.

And now my Question is:
Are those signals needed for you new Adapter or could there be a problem with the non inverted CDAC or do they simply don't matter at all?.

**Comment by LinuxJedi** [comment]
Hi,

CSYNC is needed (I wasn't aware that the A1000 didn't have that, sorry). But CDAC and the other clocks are not needed. It just needs the power, RGB and CSYNC.

**Comment by SirCathal** [comment]
Cool than it will be no problem with my machine. And soldering a cable from pin 8 on UA6 to pin 32 of the Denise socket is easy and already done at my A1000.
If everything works we can add that to the readme :-)

**Comment by SirCathal** [comment]
The adapter works fine in my A1000, see my post in:
https://github.com/LinuxJedi/AmigaRGBtoHDMI/issues/5

**Pull request merged**
